# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "product-selector-dev"
capabilities = "CAPABILITY_IAM"
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = false

[default.validate.parameters]
lint = true

[default.deploy.parameters]
confirm_changeset = false
resolve_s3 = true
stack_name = "product-selector-dev"
s3_prefix = "product-selector-dev"
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[prod.deploy.parameters]
confirm_changeset = true

[prod.build.parameters]
cached = false